### ISSUE TITLE
Fix GnogChamp crash

### ISSUE THREAD

**Issue by yakasov** [yakasov/bot-rewrite-3-js#189]
whatever this is

```cmd
Using 18.133.20.186:25565 for Minecraft query...

339133301514174465 is not present in the server!
311113624250744834 is not present in the server!

Found Minecraft server! Latency: 5
/home/opc/bot-rewrite-3-js/node_modules/@discordjs/rest/dist/index.js:722
      throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
            ^

DiscordAPIError[90001]: Reaction blocked
    at handleErrors (/home/opc/bot-rewrite-3-js/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/opc/bot-rewrite-3-js/node_modules/@discordjs/rest/dist/index.js:1120:23)
    at async SequentialHandler.queueRequest (/home/opc/bot-rewrite-3-js/node_modules/@discordjs/rest/dist/index.js:953:14)
    at async _REST.request (/home/opc/bot-rewrite-3-js/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async GuildMessageManager.react (/home/opc/bot-rewrite-3-js/node_modules/discord.js/src/managers/MessageManager.js:254:5)
    at async Message.react (/home/opc/bot-rewrite-3-js/node_modules/discord.js/src/structures/Message.js:805:5) {
  requestBody: { files: undefined, json: undefined },
  rawError: { message: 'Reaction blocked', code: 90001 },
  code: 90001,
  status: 403,
  method: 'PUT',
  url: 'https://discord.com/api/v10/channels/271381095990296576/messages/1248729952333987883/reactions/GnogChamp:813878332743090246/@me'
}

Node.js v20.11.0
[opc@instance-20240125-1645 bot-rewrite-3-js]$ 
```

**Comment by yakasov** [comment]
#191
