### ISSUE TITLE
Fix invalid displayName crash

### ISSUE THREAD

**Issue by yakasov** [yakasov/bot-rewrite-3-js#190]
```cmd
node:events:496
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'displayName')
    at getNickname (/home/opc/bot-rewrite-3-js/index.js:122:5)
    at /home/opc/bot-rewrite-3-js/index.js:228:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async f (/home/opc/bot-rewrite-3-js/index.js:224:19)
    at async Client.<anonymous> (/home/opc/bot-rewrite-3-js/index.js:668:3)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:401:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

Node.js v20.11.0
```

<img width="425" alt="image" src="https://github.com/yakasov/bot-rewrite-3-js/assets/20305423/28c43915-cbec-4ba4-9016-8e32f8548747">

I guess check if user object exists first. Thought this was fixed

**Comment by yakasov** [comment]
I reckon this happened because GitHub app 1241326553263112265 doesn't have a displayName so can be force checked against that. Also maybe common functions file ? not sure yet

**Comment by yakasov** [comment]
#191
